#!/bin/bash
set -e

npm install

# this is a temporary file that is used to fix an issue with the RN packager
# see here for more info https://github.com/facebook/react-native/issues/5467

echo "Removing duplicate version of fbjs package"
find . -name 'fbjs' -print | grep "\./node_modules/fbjs" -v | xargs rm -rf