
module.exports = {
  UPDATE_INCOME: 'UPDATE_INCOME',
  ADD_BUDGET_BLOCK: 'ADD_BUDGET_BLOCK',
  REMOVE_BUDGET_BLOCK: 'REMOVE_BUDGET_BLOCK',
  UPDATE_BUDGET_BLOCK_TITLE: 'UPDATE_BUDGET_BLOCK_TITLE',
  ADD_BUDGET_BLOCK_ITEM: 'ADD_BUDGET_BLOCK_ITEM',
  REMOVE_BUDGET_BLOCK_ITEM: 'REMOVE_BUDGET_BLOCK_ITEM',
  UPDATE_BUDGET_BLOCK_ITEM_VALUE: 'UPDATE_BUDGET_BLOCK_ITEM_VALUE',
  UPDATE_BUDGET_BLOCK_ITEM_TITLE: 'UPDATE_BUDGET_BLOCK_ITEM_TITLE',
};
